# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: myblogs
      POSTGRES_USER: dbuser
      POSTGRES_DB: myDB
    ports:
      - 5433:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  kafka:
    image: landoop/fast-data-dev
    environment:
      #ADV_HOST: 127.0.0.1         # Change to 192.168.99.100 if using Docker Toolbox
      RUNTESTS: 0                 # Disable Running tests so the cluster starts faster
    ports:
      - "3030:3030"                 # Landoop UI
      - "9092:9092"                 # Kafka Broker

  blog:
    build: .
    image: rayaanshahid/blog-post
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092